"""add created_at to prompts

Revision ID: 561c6aaa8b74
Revises: 17eee402c5c3
Create Date: 2025-04-25 20:49:44.081699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561c6aaa8b74'
down_revision = '17eee402c5c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'created_at')
    # ### end Alembic commands ### 